import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "zh-CN" | "zh-TW";

export const languageNames: Record<Language, string> = {
  en: "English",
  "zh-CN": "简体中文",
  "zh-TW": "繁體中文",
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ── Nav / Sidebar ──────────────────────────────
    "nav.appName": "CMI Dashboard",
    "nav.dashboard": "Dashboard",
    "nav.customers": "Customers",
    "nav.corporateTree": "Subsidiary Tree",
    "nav.geographic": "Geographic Map",
    "nav.aiAnalysis": "AI Analysis",
    "nav.push": "Push Notifications",
    "nav.news": "News Intelligence",
    "nav.opportunities": "Opportunities",
    "nav.pipeline": "Pipeline View",
    "nav.deals": "Deals",
    "nav.dataImport": "Data Import",
    "nav.competitors": "Competitors",
    "nav.mlAnalysis": "ML Analysis",

    // ── Common ─────────────────────────────────────
    "common.signIn": "Sign In",
    "common.signOut": "Sign Out",
    "common.language": "Language",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.search": "Search...",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.viewAll": "View All",
    "common.addNew": "Add New",
    "common.noData": "No data available",
    "common.confirm": "Confirm",
    "common.selectPlaceholder": "Please select...",

    // ── Dashboard ──────────────────────────────────
    "dashboard.title": "Customer Intelligence Dashboard",
    "dashboard.subtitle": "Track customers, opportunities, and AI-powered insights",
    "dashboard.viewCustomers": "View Targeted Customers",
    "dashboard.stats": "Statistics",
    "dashboard.recentDeals": "Recent Deals",
    "dashboard.latestNews": "Latest News",
    "dashboard.activeOpportunities": "Active Opportunities",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.totalCustomers": "Total Customers",
    "dashboard.subsidiariesTracked": "subsidiaries tracked",
    "dashboard.closedDeals": "Closed Deals",
    "dashboard.newsAlerts": "News Alerts",
    "dashboard.unreadNews": "Unread news items",
    "dashboard.opportunityPipeline": "Opportunity Pipeline",
    "dashboard.opportunityByStage": "Active opportunities by stage",
    "dashboard.revenueTrend": "Deal Revenue Trend",
    "dashboard.revenueTrendDesc": "Monthly closed deals over the past 12 months",
    "dashboard.noOpportunityData": "No opportunity data available",
    "dashboard.addOpportunities": "Add Opportunities",
    "dashboard.noDealData": "No deal data available",
    "dashboard.addDeals": "Add Deals",
    "dashboard.latestDeals": "Latest closed transactions",
    "dashboard.recentNewsDesc": "Recent customer-related news",
    "dashboard.noDealRecords": "No deals recorded yet",
    "dashboard.noNewsItems": "No news items yet",

    // ── Customers ──────────────────────────────────
    "customers.title": "Customers",
    "customers.subtitle": "Manage enterprise accounts and corporate profiles",
    "customers.addCustomer": "Add Customer",
    "customers.addNewCustomer": "Add New Customer",
    "customers.createDesc": "Create a new customer profile. You can add more details later.",
    "customers.companyName": "Company Name",
    "customers.companyNamePlaceholder": "e.g., Acme Corporation",
    "customers.industry": "Industry",
    "customers.industryPlaceholder": "e.g., Technology",
    "customers.country": "Country",
    "customers.countryPlaceholder": "e.g., United States",
    "customers.website": "Website",
    "customers.websitePlaceholder": "e.g., https://example.com",
    "customers.employees": "Employees",
    "customers.employeesPlaceholder": "e.g., 5000",
    "customers.annualRevenue": "Annual Revenue ($)",
    "customers.revenuePlaceholder": "e.g., 10000000",
    "customers.creating": "Creating...",
    "customers.createCustomer": "Create Customer",
    "customers.searchPlaceholder": "Search customers...",
    "customers.noFound": "No customers found",
    "customers.noFoundDesc": "Get started by adding your first customer",
    "customers.tryAdjust": "Try adjusting your search terms",
    "customers.revenue": "Revenue",
    "customers.status": "Status",
    "customers.active": "Active",
    "customers.visit": "Visit",

    // ── Corporate Tree ─────────────────────────────
    "corporateTree.title": "Corporate Family Tree",
    "corporateTree.subtitle": "Visualize corporate structure and subsidiaries",
    "corporateTree.selectCompany": "Select Company",
    "corporateTree.selectDesc": "Choose a parent company to view its corporate structure",
    "corporateTree.choosePlaceholder": "Choose a company...",
    "corporateTree.noCustomers": "No customers available. Add customers first.",
    "corporateTree.structure": "Corporate Structure",
    "corporateTree.subsidiariesCount": "subsidiaries and branches",
    "corporateTree.noSubsidiaries": "No subsidiaries added yet for this company.",
    "corporateTree.addSubsidiary": "Add Subsidiary",
    "corporateTree.selectPrompt": "Select a company to view its structure",
    "corporateTree.selectPromptDesc": "The corporate family tree will display parent company, subsidiaries, and branches",
    "corporateTree.entityTypes": "Entity Types",
    "corporateTree.parentCompany": "Parent Company",
    "corporateTree.parentDesc": "Main corporate entity",
    "corporateTree.subsidiary": "Subsidiary",
    "corporateTree.subsidiaryDesc": "Owned entity",
    "corporateTree.branch": "Branch",
    "corporateTree.branchDesc": "Regional office",
    "corporateTree.affiliate": "Affiliate",
    "corporateTree.affiliateDesc": "Related entity",

    // ── Geographic Map ─────────────────────────────
    "geographic.title": "Geographic Distribution",
    "geographic.subtitle": "Visualize subsidiary and branch locations worldwide",
    "geographic.allCustomers": "All Customers",
    "geographic.totalLocations": "Total Locations",
    "geographic.headquarters": "Headquarters",
    "geographic.subsidiaries": "Subsidiaries",
    "geographic.branches": "Branches",
    "geographic.inactive": "Inactive",
    "geographic.globalMap": "Global Presence Map",
    "geographic.loading": "Loading locations...",
    "geographic.showing": "Showing",
    "geographic.locations": "locations.",
    "geographic.noLocations": "No locations found",
    "geographic.topCountries": "Top Countries",
    "geographic.byCountry": "Locations by country",
    "geographic.locationDetails": "Location Details",
    "geographic.selectMarker": "Select a marker on the map",
    "geographic.entityName": "Entity Name",
    "geographic.type": "Type",
    "geographic.coordinates": "Coordinates",
    "geographic.allLocations": "All Locations",
    "geographic.completeList": "Complete list of geographic locations",
    "geographic.total": "total",
    "geographic.clickMarker": "Click on a map marker to view details",
    "geographic.filterByCustomer": "Filter by customer",
    "geographic.noCoordinatesTitle": "No map data available for this customer",
    "geographic.noCoordinatesDesc": "This customer has subsidiaries but none have GPS coordinates",
    "geographic.noCoordinatesShort": "No map markers (missing coordinates)",
    "geographic.noCoordinatesHint": "Add latitude/longitude to subsidiaries to display them on the map",
    "geographic.entries": "entries",
    "geographic.missingCoords": "missing coordinates",
    "geographic.noCoords": "No coordinates",
    "geographic.hq": "Headquarters",
    "geographic.mapTitle": "Global Presence Map",
    "geographic.locationsOnMap": "locations on map",
    "geographic.noMapData": "No map data available",
    "geographic.loadingMap": "Loading map...",
    "geographic.selectCustomerHint": "Select a customer to view locations",
    "geographic.missingCoordsDesc": "The following entries are missing GPS coordinates",
    "geographic.countryDist": "Country Distribution",
    "geographic.entityList": "All Locations",
    "geographic.name": "Name",

    // ── AI Analysis ────────────────────────────────
    "aiAnalysis.title": "AI Analysis",
    "aiAnalysis.subtitle": "Generate AI-powered insights for your customers",
    "aiAnalysis.generateTitle": "Generate Analysis",
    "aiAnalysis.generateDesc": "Select a customer and analysis type to generate insights",
    "aiAnalysis.selectCustomer": "Select Customer",
    "aiAnalysis.choosePlaceholder": "Choose a customer...",
    "aiAnalysis.analysisType": "Analysis Type",
    "aiAnalysis.analyzing": "Analyzing...",
    "aiAnalysis.generate": "Generate Analysis",
    "aiAnalysis.resultTitle": "Analysis Result",
    "aiAnalysis.forCustomer": "for selected customer",
    "aiAnalysis.noResult": "No analysis generated yet",
    "aiAnalysis.noResultDesc": "Select a customer and click \"Generate Analysis\" to get started",
    "aiAnalysis.summary": "Executive Summary",
    "aiAnalysis.summaryDesc": "Comprehensive overview for sales meetings",
    "aiAnalysis.productMatch": "Product Matching",
    "aiAnalysis.productMatchDesc": "Recommend relevant products and services",
    "aiAnalysis.talkingPoints": "Talking Points",
    "aiAnalysis.talkingPointsDesc": "Generate conversation starters and strategies",
    "aiAnalysis.riskAssessment": "Risk Assessment",
    "aiAnalysis.riskAssessmentDesc": "Evaluate business relationship risks",

    // ── News ───────────────────────────────────────
    "news.title": "News & Insights",
    "news.subtitle": "Customer-related news with AI analysis",
    "news.importExcel": "Import Excel",
    "news.searchTitle": "News Search",
    "news.targetCustomer": "Target Customer",
    "news.selectCompany": "Select a company...",
    "news.searching": "Searching...",
    "news.searchNews": "Search News",
    "news.latestNews": "Latest News",
    "news.latestNewsDesc": "News articles related to your customers",
    "news.noNews": "No news found",
    "news.noNewsDesc": "Select a customer above and click \"Search News\" to start!",
    "news.aiAnalysis": "AI Analysis",
    "news.verifySource": "Verify Source",
    "news.webSource": "Web Source",

    // ── Opportunities ──────────────────────────────
    "opportunities.title": "Opportunities",
    "opportunities.subtitle": "Track and manage business opportunities",
    "opportunities.total": "Total Opportunities",
    "opportunities.active": "Active",
    "opportunities.pipelineValue": "Pipeline Value",
    "opportunities.pipeline": "Opportunity Pipeline",
    "opportunities.pipelineDesc": "All tracked opportunities",
    "opportunities.noData": "No opportunities yet",
    "opportunities.noDataDesc": "Add opportunities to track your sales pipeline",
    "opportunities.general": "General",

    // ── Deals ──────────────────────────────────────
    "deals.title": "Deals",
    "deals.subtitle": "Closed transactions and deal history",
    "deals.total": "Total Deals",
    "deals.totalValue": "Total Value",
    "deals.activeContracts": "Active Contracts",
    "deals.history": "Deal History",
    "deals.historyDesc": "All closed transactions",
    "deals.noDeals": "No deals recorded yet",
    "deals.noDealsDesc": "Closed deals will appear here",
    "deals.general": "General",

    // ── Data Import ────────────────────────────────
    "dataImport.title": "Data Import",
    "dataImport.subtitle": "Batch import customers, deals, opportunities, BHI projects and AI recommendations",
    "dataImport.uploadTitle": "Upload File",
    "dataImport.uploadDesc": "Select an Excel (.xlsx) or CSV file",
    "dataImport.clickToUpload": "Click to upload, or drag and drop a file here",
    "dataImport.autoDetect": "Supports automatic detection of Chinese and English column headers",
    "dataImport.selectFile": "Select File",
    "dataImport.parsing": "Parsing file...",
    "dataImport.loginRequired": "Please log in before importing data",
    "dataImport.previewTitle": "Preview",
    "dataImport.rowsDetected": "rows of data detected. Please confirm the import type.",
    "dataImport.dataTypeLabel": "What data are you importing?",
    "dataImport.cancel": "Cancel",
    "dataImport.importing": "Importing to database...",
    "dataImport.confirmImport": "Confirm Import",
    "dataImport.rows": "rows",
    "dataImport.previewNote": "(Showing first 5 rows preview)",
    "dataImport.history": "Import History",
    "dataImport.historyDesc": "Recent file processing records",
    "dataImport.noHistory": "No import records yet",
    "dataImport.success": "Success",
    "dataImport.failed": "Failed",
    "dataImport.total": "Total",

    // ── Push Notifications ─────────────────────────
    "push.title": "Push Notifications",
    "push.subtitle": "Send messages to regional sales teams",

    // ── Competitors ────────────────────────────────
    "competitors.title": "Competitors",
    "competitors.subtitle": "Track and analyze competitor intelligence",

    // ── ML Analysis ────────────────────────────────
    "ml.title": "Global Strategy Dashboard",
    "ml.subtitle": "AI-Powered investment insights and project recommendations based on BHI data",
    "ml.totalProjects": "Total Projects",
    "ml.totalInvestment": "Total Investment",
    "ml.aiMatches": "AI High Matches",
    "ml.searchPlaceholder": "Search projects, countries or products...",
    "ml.sectorChart": "Investment by Sector",
    "ml.sectorPie": "Sector Distribution",

    // ── Pipeline ────────────────────────────────
    "pipeline.title": "Opportunity Pipeline",
    "pipeline.subtitle": "Track and analyze business opportunities across products and regions",
    "pipeline.selectPeriod": "Select period",
    "pipeline.reserveAmount": "Pipeline Reserve",
    "pipeline.unitBillionHKD": "Bn HKD",
    "pipeline.unitBillion": "Bn",
    "pipeline.unitWan": "Wan",
    "pipeline.unitWanHKD": "Wan HKD",
    "pipeline.reserveDesc": "Scope: Opportunities created in the last 6 months with win rate >30%, excluding archived/cancelled",
    "pipeline.lastYear": "Last Year",
    "pipeline.thisYear": "This Year",
    "pipeline.structure": "Opportunity Structure",
    "pipeline.low": "Win Rate < 30%",
    "pipeline.medium": "30% ≤ Win Rate < 80%",
    "pipeline.high": "Win Rate ≥ 80%",
    "pipeline.productDist": "Pipeline by Product",
    "pipeline.productUnit": "Unit: Wan HKD",
    "pipeline.trendTitle": "Monthly Opportunity Trend",
    "pipeline.trendDesc": "Track opportunity value and count over time",
    "pipeline.amountBillion": "Amount (Bn)",
    "pipeline.count": "Count",
    "pipeline.amountLegend": "Amount (Bn HKD)",
    "pipeline.countLegend": "Count",
    "pipeline.productTitle": "Opportunity by Product",
    "pipeline.productDesc": "Detailed breakdown of opportunities by product line",
    "pipeline.amount": "Amount",
  },

  "zh-CN": {
    // ── 导航栏 ─────────────────────────────────────
    "nav.appName": "CMI 战略仪表盘",
    "nav.dashboard": "总览仪表盘",
    "nav.customers": "客户管理",
    "nav.corporateTree": "子公司树状图",
    "nav.geographic": "地理分布图",
    "nav.aiAnalysis": "AI 智能分析",
    "nav.push": "消息推送",
    "nav.news": "新闻情报",
    "nav.opportunities": "商机管理",
    "nav.pipeline": "销售漏斗",
    "nav.deals": "成交订单",
    "nav.dataImport": "数据导入",
    "nav.competitors": "竞争对手",
    "nav.mlAnalysis": "机器学习分析",

    // ── 通用 ───────────────────────────────────────
    "common.signIn": "登录",
    "common.signOut": "退出登录",
    "common.language": "语言",
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.view": "查看",
    "common.search": "搜索...",
    "common.filter": "筛选",
    "common.export": "导出",
    "common.viewAll": "查看全部",
    "common.addNew": "新增",
    "common.noData": "暂无数据",
    "common.confirm": "确认",
    "common.selectPlaceholder": "请选择...",

    // ── 总览仪表盘 ─────────────────────────────────
    "dashboard.title": "客户智能管理平台",
    "dashboard.subtitle": "追踪客户动态、商机与 AI 洞察",
    "dashboard.viewCustomers": "查看目标客户",
    "dashboard.stats": "核心指标",
    "dashboard.recentDeals": "最近成交",
    "dashboard.latestNews": "最新情报",
    "dashboard.activeOpportunities": "活跃商机",
    "dashboard.totalRevenue": "总营收",
    "dashboard.totalCustomers": "客户总数",
    "dashboard.subsidiariesTracked": "个子公司追踪中",
    "dashboard.closedDeals": "已成交订单",
    "dashboard.newsAlerts": "新闻提醒",
    "dashboard.unreadNews": "条未读新闻",
    "dashboard.opportunityPipeline": "商机漏斗",
    "dashboard.opportunityByStage": "各阶段活跃商机分布",
    "dashboard.revenueTrend": "成单收入趋势",
    "dashboard.revenueTrendDesc": "过去 12 个月月度成单数据",
    "dashboard.noOpportunityData": "暂无商机数据",
    "dashboard.addOpportunities": "添加商机",
    "dashboard.noDealData": "暂无成单数据",
    "dashboard.addDeals": "添加成单",
    "dashboard.latestDeals": "最近成交记录",
    "dashboard.recentNewsDesc": "客户相关近期新闻",
    "dashboard.noDealRecords": "暂无成单记录",
    "dashboard.noNewsItems": "暂无新闻条目",

    // ── 客户管理 ───────────────────────────────────
    "customers.title": "客户管理",
    "customers.subtitle": "管理企业客户档案与公司主体信息",
    "customers.addCustomer": "添加客户",
    "customers.addNewCustomer": "新增客户",
    "customers.createDesc": "创建新的客户档案，后续可补充更多详细信息。",
    "customers.companyName": "公司名称",
    "customers.companyNamePlaceholder": "例如：阿里巴巴集团",
    "customers.industry": "行业",
    "customers.industryPlaceholder": "例如：互联网",
    "customers.country": "国家/地区",
    "customers.countryPlaceholder": "例如：中国",
    "customers.website": "官网",
    "customers.websitePlaceholder": "例如：https://example.com",
    "customers.employees": "员工数",
    "customers.employeesPlaceholder": "例如：5000",
    "customers.annualRevenue": "年收入（$）",
    "customers.revenuePlaceholder": "例如：10000000",
    "customers.creating": "创建中...",
    "customers.createCustomer": "创建客户",
    "customers.searchPlaceholder": "搜索客户...",
    "customers.noFound": "未找到客户",
    "customers.noFoundDesc": "添加第一个客户以开始使用",
    "customers.tryAdjust": "请尝试调整搜索关键词",
    "customers.revenue": "年收入",
    "customers.status": "状态",
    "customers.active": "运营中",
    "customers.visit": "访问",

    // ── 子公司树状图 ───────────────────────────────
    "corporateTree.title": "子公司树状图",
    "corporateTree.subtitle": "可视化企业股权结构与子公司关系",
    "corporateTree.selectCompany": "选择公司",
    "corporateTree.selectDesc": "选择一家母公司以查看其企业架构",
    "corporateTree.choosePlaceholder": "请选择公司...",
    "corporateTree.noCustomers": "暂无客户数据，请先添加客户。",
    "corporateTree.structure": "企业架构",
    "corporateTree.subsidiariesCount": "个子公司和分支机构",
    "corporateTree.noSubsidiaries": "该公司暂未添加子公司。",
    "corporateTree.addSubsidiary": "添加子公司",
    "corporateTree.selectPrompt": "请选择一家公司以查看其架构",
    "corporateTree.selectPromptDesc": "企业家族树将展示母公司、子公司及分支机构的完整关系",
    "corporateTree.entityTypes": "实体类型说明",
    "corporateTree.parentCompany": "母公司",
    "corporateTree.parentDesc": "核心法人主体",
    "corporateTree.subsidiary": "子公司",
    "corporateTree.subsidiaryDesc": "控股子实体",
    "corporateTree.branch": "分支机构",
    "corporateTree.branchDesc": "区域办事处",
    "corporateTree.affiliate": "关联公司",
    "corporateTree.affiliateDesc": "关联实体",

    // ── 地理分布图 ─────────────────────────────────
    "geographic.title": "地理分布图",
    "geographic.subtitle": "全球子公司与分支机构位置可视化",
    "geographic.allCustomers": "全部客户",
    "geographic.totalLocations": "总据点数",
    "geographic.headquarters": "总部",
    "geographic.subsidiaries": "子公司",
    "geographic.branches": "分支机构",
    "geographic.inactive": "已停止运营",
    "geographic.globalMap": "全球分布地图",
    "geographic.loading": "正在加载位置数据...",
    "geographic.showing": "显示",
    "geographic.locations": "个据点。",
    "geographic.noLocations": "未找到位置数据",
    "geographic.topCountries": "国家分布 Top 10",
    "geographic.byCountry": "按国家统计据点数量",
    "geographic.locationDetails": "位置详情",
    "geographic.selectMarker": "点击地图上的标记查看详情",
    "geographic.entityName": "实体名称",
    "geographic.type": "类型",
    "geographic.coordinates": "坐标",
    "geographic.allLocations": "全部位置",
    "geographic.completeList": "所有地理位置完整列表",
    "geographic.total": "共",
    "geographic.clickMarker": "点击地图标记查看详细信息",
    "geographic.filterByCustomer": "按客户筛选",
    "geographic.noCoordinatesTitle": "该客户暂无地图数据",
    "geographic.noCoordinatesDesc": "该客户有子公司记录，但尚未填写经纬度坐标",
    "geographic.noCoordinatesShort": "无地图标记（缺少坐标）",
    "geographic.noCoordinatesHint": "请在子公司记录中填写经纬度，即可在地图上显示",
    "geographic.entries": "条记录",
    "geographic.missingCoords": "条缺少坐标",
    "geographic.noCoords": "无坐标",
    "geographic.hq": "总部",
    "geographic.mapTitle": "全球分布地图",
    "geographic.locationsOnMap": "个据点显示在地图上",
    "geographic.noMapData": "暂无地图数据",
    "geographic.loadingMap": "地图加载中...",
    "geographic.selectCustomerHint": "选择客户以查看位置",
    "geographic.missingCoordsDesc": "以下记录缺少 GPS 坐标",
    "geographic.countryDist": "国家分布",
    "geographic.entityList": "全部位置",
    "geographic.name": "名称",

    // ── AI 智能分析 ────────────────────────────────
    "aiAnalysis.title": "AI 智能分析",
    "aiAnalysis.subtitle": "为您的客户生成 AI 驱动的深度洞察报告",
    "aiAnalysis.generateTitle": "生成分析报告",
    "aiAnalysis.generateDesc": "选择客户和分析类型，一键生成洞察内容",
    "aiAnalysis.selectCustomer": "选择客户",
    "aiAnalysis.choosePlaceholder": "请选择客户...",
    "aiAnalysis.analysisType": "分析类型",
    "aiAnalysis.analyzing": "分析中...",
    "aiAnalysis.generate": "生成分析",
    "aiAnalysis.resultTitle": "分析结果",
    "aiAnalysis.forCustomer": "（针对已选客户）",
    "aiAnalysis.noResult": "尚未生成分析报告",
    "aiAnalysis.noResultDesc": "请选择客户后点击「生成分析」开始使用",
    "aiAnalysis.summary": "执行摘要",
    "aiAnalysis.summaryDesc": "为销售会议生成客户全面概览",
    "aiAnalysis.productMatch": "产品匹配",
    "aiAnalysis.productMatchDesc": "推荐适合该客户的产品与服务",
    "aiAnalysis.talkingPoints": "对话要点",
    "aiAnalysis.talkingPointsDesc": "生成拜访前的谈话策略与开场白",
    "aiAnalysis.riskAssessment": "风险评估",
    "aiAnalysis.riskAssessmentDesc": "评估与该客户合作的潜在风险",

    // ── 新闻情报 ───────────────────────────────────
    "news.title": "新闻情报",
    "news.subtitle": "客户相关新闻与 AI 智能分析",
    "news.importExcel": "导入 Excel",
    "news.searchTitle": "新闻搜索",
    "news.targetCustomer": "目标客户",
    "news.selectCompany": "请选择公司...",
    "news.searching": "搜索中...",
    "news.searchNews": "搜索新闻",
    "news.latestNews": "最新新闻",
    "news.latestNewsDesc": "与您客户相关的新闻资讯",
    "news.noNews": "暂无新闻",
    "news.noNewsDesc": "请在上方选择客户并点击「搜索新闻」开始使用",
    "news.aiAnalysis": "AI 分析",
    "news.verifySource": "验证来源",
    "news.webSource": "网络来源",

    // ── 商机管理 ───────────────────────────────────
    "opportunities.title": "商机管理",
    "opportunities.subtitle": "追踪与管理销售商机全周期",
    "opportunities.total": "商机总数",
    "opportunities.active": "活跃商机",
    "opportunities.pipelineValue": "管道总金额",
    "opportunities.pipeline": "商机漏斗",
    "opportunities.pipelineDesc": "全部追踪中的商机",
    "opportunities.noData": "暂无商机数据",
    "opportunities.noDataDesc": "添加商机以开始追踪销售管道",
    "opportunities.general": "通用",

    // ── 成交订单 ───────────────────────────────────
    "deals.title": "成交订单",
    "deals.subtitle": "已成交订单记录与历史数据",
    "deals.total": "订单总数",
    "deals.totalValue": "总金额",
    "deals.activeContracts": "活跃合同金额",
    "deals.history": "成单历史",
    "deals.historyDesc": "全部已成交记录",
    "deals.noDeals": "暂无成单记录",
    "deals.noDealsDesc": "成交订单将在此处显示",
    "deals.general": "通用",

    // ── 数据导入 ───────────────────────────────────
    "dataImport.title": "数据导入",
    "dataImport.subtitle": "支持批量导入客户、订单、商机、BHI 项目库及 AI 推荐数据",
    "dataImport.uploadTitle": "上传文件",
    "dataImport.uploadDesc": "选择 Excel (.xlsx) 或 CSV 文件",
    "dataImport.clickToUpload": "点击此处上传，或拖拽文件到这里",
    "dataImport.autoDetect": "支持自动识别中英文表头",
    "dataImport.selectFile": "选择文件",
    "dataImport.parsing": "正在解析文件...",
    "dataImport.loginRequired": "请先登录系统再进行操作",
    "dataImport.previewTitle": "预览",
    "dataImport.rowsDetected": "行数据，请确认导入类型",
    "dataImport.dataTypeLabel": "你要导入什么数据？",
    "dataImport.cancel": "取消",
    "dataImport.importing": "正在导入数据库...",
    "dataImport.confirmImport": "确认导入",
    "dataImport.rows": "条数据",
    "dataImport.previewNote": "（仅显示前 5 行预览）",
    "dataImport.history": "导入历史",
    "dataImport.historyDesc": "最近的文件处理记录",
    "dataImport.noHistory": "暂无导入记录",
    "dataImport.success": "成功",
    "dataImport.failed": "失败",
    "dataImport.total": "共",

    // ── 消息推送 ───────────────────────────────────
    "push.title": "消息推送",
    "push.subtitle": "向各区域销售团队发送通知消息",

    // ── 竞争对手 ───────────────────────────────────
    "competitors.title": "竞争对手",
    "competitors.subtitle": "追踪与分析竞争对手情报",

    // ── 机器学习分析 ───────────────────────────────
    "ml.title": "全球战略仪表盘",
    "ml.subtitle": "基于 BHI 项目库与 AI 混合推荐模型的商机分析系统",
    "ml.totalProjects": "项目总数",
    "ml.totalInvestment": "涉及投资总额",
    "ml.aiMatches": "AI 高匹配商机",
    "ml.searchPlaceholder": "搜索项目、国家或推荐产品...",
    "ml.sectorChart": "行业投资热度 (Top 8)",
    "ml.sectorPie": "行业分布占比",

    // ── 销售漏斗 ───────────────────────────────
    "pipeline.title": "销售漏斗",
    "pipeline.subtitle": "追踪与分析各产品线及区域的商机储备情况",
    "pipeline.selectPeriod": "选择时间段",
    "pipeline.reserveAmount": "商机储备金额",
    "pipeline.unitBillionHKD": "亿港币",
    "pipeline.unitBillion": "亿",
    "pipeline.unitWan": "万",
    "pipeline.unitWanHKD": "万港币",
    "pipeline.reserveDesc": "口径：创建时间在近6个月成单率>30%且不含已归档取消的商机的港币金额总值",
    "pipeline.lastYear": "上年",
    "pipeline.thisYear": "今年",
    "pipeline.structure": "商机结构分布",
    "pipeline.low": "商机赢率 < 30%",
    "pipeline.medium": "30% ≤ 商机赢率 < 80%",
    "pipeline.high": "商机赢率 ≥ 80%",
    "pipeline.productDist": "商机金额分布（按产品）",
    "pipeline.productUnit": "单位：万港币",
    "pipeline.trendTitle": "月度商机趋势",
    "pipeline.trendDesc": "追踪商机价值与数量随时间的变化",
    "pipeline.amountBillion": "金额（亿）",
    "pipeline.count": "数量",
    "pipeline.amountLegend": "金额（亿港币）",
    "pipeline.countLegend": "数量",
    "pipeline.productTitle": "产品商机分布",
    "pipeline.productDesc": "按产品线细分的商机详情",
    "pipeline.amount": "金额",
  },

  "zh-TW": {
    // ── 導航欄 ─────────────────────────────────────
    "nav.appName": "CMI 戰略儀表板",
    "nav.dashboard": "總覽儀表板",
    "nav.customers": "客戶管理",
    "nav.corporateTree": "子公司樹狀圖",
    "nav.geographic": "地理分佈圖",
    "nav.aiAnalysis": "AI 智能分析",
    "nav.push": "消息推送",
    "nav.news": "新聞情報",
    "nav.opportunities": "商機管理",
    "nav.pipeline": "銷售漏斗",
    "nav.deals": "成交訂單",
    "nav.dataImport": "數據導入",
    "nav.competitors": "競爭對手",
    "nav.mlAnalysis": "機器學習分析",

    // ── 通用 ───────────────────────────────────────
    "common.signIn": "登入",
    "common.signOut": "登出",
    "common.language": "語言",
    "common.loading": "加載中...",
    "common.error": "發生錯誤",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.delete": "刪除",
    "common.edit": "編輯",
    "common.view": "查看",
    "common.search": "搜尋...",
    "common.filter": "篩選",
    "common.export": "導出",
    "common.viewAll": "查看全部",
    "common.addNew": "新增",
    "common.noData": "暫無數據",
    "common.confirm": "確認",
    "common.selectPlaceholder": "請選擇...",

    // ── 總覽儀表板 ─────────────────────────────────
    "dashboard.title": "客戶智能管理平台",
    "dashboard.subtitle": "追蹤客戶動態、商機與 AI 洞察",
    "dashboard.viewCustomers": "查看目標客戶",
    "dashboard.stats": "核心指標",
    "dashboard.recentDeals": "最近成交",
    "dashboard.latestNews": "最新情報",
    "dashboard.activeOpportunities": "活躍商機",
    "dashboard.totalRevenue": "總營收",
    "dashboard.totalCustomers": "客戶總數",
    "dashboard.subsidiariesTracked": "個子公司追蹤中",
    "dashboard.closedDeals": "已成交訂單",
    "dashboard.newsAlerts": "新聞提醒",
    "dashboard.unreadNews": "條未讀新聞",
    "dashboard.opportunityPipeline": "商機漏斗",
    "dashboard.opportunityByStage": "各階段活躍商機分佈",
    "dashboard.revenueTrend": "成單收入趨勢",
    "dashboard.revenueTrendDesc": "過去 12 個月月度成單數據",
    "dashboard.noOpportunityData": "暫無商機數據",
    "dashboard.addOpportunities": "添加商機",
    "dashboard.noDealData": "暫無成單數據",
    "dashboard.addDeals": "添加成單",
    "dashboard.latestDeals": "最近成交記錄",
    "dashboard.recentNewsDesc": "客戶相關近期新聞",
    "dashboard.noDealRecords": "暫無成單記錄",
    "dashboard.noNewsItems": "暫無新聞條目",

    // ── 客戶管理 ───────────────────────────────────
    "customers.title": "客戶管理",
    "customers.subtitle": "管理企業客戶檔案與公司主體信息",
    "customers.addCustomer": "添加客戶",
    "customers.addNewCustomer": "新增客戶",
    "customers.createDesc": "建立新的客戶檔案，後續可補充更多詳細資訊。",
    "customers.companyName": "公司名稱",
    "customers.companyNamePlaceholder": "例如：阿里巴巴集團",
    "customers.industry": "行業",
    "customers.industryPlaceholder": "例如：互聯網",
    "customers.country": "國家/地區",
    "customers.countryPlaceholder": "例如：中國",
    "customers.website": "官網",
    "customers.websitePlaceholder": "例如：https://example.com",
    "customers.employees": "員工數",
    "customers.employeesPlaceholder": "例如：5000",
    "customers.annualRevenue": "年收入（$）",
    "customers.revenuePlaceholder": "例如：10000000",
    "customers.creating": "建立中...",
    "customers.createCustomer": "建立客戶",
    "customers.searchPlaceholder": "搜尋客戶...",
    "customers.noFound": "未找到客戶",
    "customers.noFoundDesc": "添加第一個客戶以開始使用",
    "customers.tryAdjust": "請嘗試調整搜尋關鍵詞",
    "customers.revenue": "年收入",
    "customers.status": "狀態",
    "customers.active": "運營中",
    "customers.visit": "訪問",

    // ── 子公司樹狀圖 ───────────────────────────────
    "corporateTree.title": "子公司樹狀圖",
    "corporateTree.subtitle": "可視化企業股權結構與子公司關係",
    "corporateTree.selectCompany": "選擇公司",
    "corporateTree.selectDesc": "選擇一家母公司以查看其企業架構",
    "corporateTree.choosePlaceholder": "請選擇公司...",
    "corporateTree.noCustomers": "暫無客戶數據，請先添加客戶。",
    "corporateTree.structure": "企業架構",
    "corporateTree.subsidiariesCount": "個子公司和分支機構",
    "corporateTree.noSubsidiaries": "該公司暫未添加子公司。",
    "corporateTree.addSubsidiary": "添加子公司",
    "corporateTree.selectPrompt": "請選擇一家公司以查看其架構",
    "corporateTree.selectPromptDesc": "企業家族樹將展示母公司、子公司及分支機構的完整關係",
    "corporateTree.entityTypes": "實體類型說明",
    "corporateTree.parentCompany": "母公司",
    "corporateTree.parentDesc": "核心法人主體",
    "corporateTree.subsidiary": "子公司",
    "corporateTree.subsidiaryDesc": "控股子實體",
    "corporateTree.branch": "分支機構",
    "corporateTree.branchDesc": "區域辦事處",
    "corporateTree.affiliate": "關聯公司",
    "corporateTree.affiliateDesc": "關聯實體",

    // ── 地理分佈圖 ─────────────────────────────────
    "geographic.title": "地理分佈圖",
    "geographic.subtitle": "全球子公司與分支機構位置可視化",
    "geographic.allCustomers": "全部客戶",
    "geographic.totalLocations": "總據點數",
    "geographic.headquarters": "總部",
    "geographic.subsidiaries": "子公司",
    "geographic.branches": "分支機構",
    "geographic.inactive": "已停止運營",
    "geographic.globalMap": "全球分佈地圖",
    "geographic.loading": "正在加載位置數據...",
    "geographic.showing": "顯示",
    "geographic.locations": "個據點。",
    "geographic.noLocations": "未找到位置數據",
    "geographic.topCountries": "國家分佈 Top 10",
    "geographic.byCountry": "按國家統計據點數量",
    "geographic.locationDetails": "位置詳情",
    "geographic.selectMarker": "點擊地圖上的標記查看詳情",
    "geographic.entityName": "實體名稱",
    "geographic.type": "類型",
    "geographic.coordinates": "坐標",
    "geographic.allLocations": "全部位置",
    "geographic.completeList": "所有地理位置完整列表",
    "geographic.total": "共",
    "geographic.clickMarker": "點擊地圖標記查看詳細信息",
    "geographic.filterByCustomer": "按客戶篩選",
    "geographic.noCoordinatesTitle": "該客戶暫無地圖數據",
    "geographic.noCoordinatesDesc": "該客戶有子公司記錄，但尚未填寫經緯度座標",
    "geographic.noCoordinatesShort": "無地圖標記（缺少座標）",
    "geographic.noCoordinatesHint": "請在子公司記錄中填寫經緯度，即可在地圖上顯示",
    "geographic.entries": "條記錄",
    "geographic.missingCoords": "條缺少座標",
    "geographic.noCoords": "無座標",
    "geographic.hq": "總部",
    "geographic.mapTitle": "全球分佈地圖",
    "geographic.locationsOnMap": "個據點顯示在地圖上",
    "geographic.noMapData": "暫無地圖數據",
    "geographic.loadingMap": "地圖加載中...",
    "geographic.selectCustomerHint": "選擇客戶以查看位置",
    "geographic.missingCoordsDesc": "以下記錄缺少 GPS 座標",
    "geographic.countryDist": "國家分佈",
    "geographic.entityList": "全部位置",
    "geographic.name": "名稱",

    // ── AI 智能分析 ────────────────────────────────
    "aiAnalysis.title": "AI 智能分析",
    "aiAnalysis.subtitle": "為您的客戶生成 AI 驅動的深度洞察報告",
    "aiAnalysis.generateTitle": "生成分析報告",
    "aiAnalysis.generateDesc": "選擇客戶和分析類型，一鍵生成洞察內容",
    "aiAnalysis.selectCustomer": "選擇客戶",
    "aiAnalysis.choosePlaceholder": "請選擇客戶...",
    "aiAnalysis.analysisType": "分析類型",
    "aiAnalysis.analyzing": "分析中...",
    "aiAnalysis.generate": "生成分析",
    "aiAnalysis.resultTitle": "分析結果",
    "aiAnalysis.forCustomer": "（針對已選客戶）",
    "aiAnalysis.noResult": "尚未生成分析報告",
    "aiAnalysis.noResultDesc": "請選擇客戶後點擊「生成分析」開始使用",
    "aiAnalysis.summary": "執行摘要",
    "aiAnalysis.summaryDesc": "為銷售會議生成客戶全面概覽",
    "aiAnalysis.productMatch": "產品匹配",
    "aiAnalysis.productMatchDesc": "推薦適合該客戶的產品與服務",
    "aiAnalysis.talkingPoints": "對話要點",
    "aiAnalysis.talkingPointsDesc": "生成拜訪前的談話策略與開場白",
    "aiAnalysis.riskAssessment": "風險評估",
    "aiAnalysis.riskAssessmentDesc": "評估與該客戶合作的潛在風險",

    // ── 新聞情報 ───────────────────────────────────
    "news.title": "新聞情報",
    "news.subtitle": "客戶相關新聞與 AI 智能分析",
    "news.importExcel": "導入 Excel",
    "news.searchTitle": "新聞搜尋",
    "news.targetCustomer": "目標客戶",
    "news.selectCompany": "請選擇公司...",
    "news.searching": "搜尋中...",
    "news.searchNews": "搜尋新聞",
    "news.latestNews": "最新新聞",
    "news.latestNewsDesc": "與您客戶相關的新聞資訊",
    "news.noNews": "暫無新聞",
    "news.noNewsDesc": "請在上方選擇客戶並點擊「搜尋新聞」開始使用",
    "news.aiAnalysis": "AI 分析",
    "news.verifySource": "驗證來源",
    "news.webSource": "網絡來源",

    // ── 商機管理 ───────────────────────────────────
    "opportunities.title": "商機管理",
    "opportunities.subtitle": "追蹤與管理銷售商機全週期",
    "opportunities.total": "商機總數",
    "opportunities.active": "活躍商機",
    "opportunities.pipelineValue": "管道總金額",
    "opportunities.pipeline": "商機漏斗",
    "opportunities.pipelineDesc": "全部追蹤中的商機",
    "opportunities.noData": "暫無商機數據",
    "opportunities.noDataDesc": "添加商機以開始追蹤銷售管道",
    "opportunities.general": "通用",

    // ── 成交訂單 ───────────────────────────────────
    "deals.title": "成交訂單",
    "deals.subtitle": "已成交訂單記錄與歷史數據",
    "deals.total": "訂單總數",
    "deals.totalValue": "總金額",
    "deals.activeContracts": "活躍合同金額",
    "deals.history": "成單歷史",
    "deals.historyDesc": "全部已成交記錄",
    "deals.noDeals": "暫無成單記錄",
    "deals.noDealsDesc": "成交訂單將在此處顯示",
    "deals.general": "通用",

    // ── 數據導入 ───────────────────────────────────
    "dataImport.title": "數據導入",
    "dataImport.subtitle": "支持批量導入客戶、訂單、商機、BHI 項目庫及 AI 推薦數據",
    "dataImport.uploadTitle": "上傳文件",
    "dataImport.uploadDesc": "選擇 Excel (.xlsx) 或 CSV 文件",
    "dataImport.clickToUpload": "點擊此處上傳，或拖拽文件到這裡",
    "dataImport.autoDetect": "支持自動識別中英文表頭",
    "dataImport.selectFile": "選擇文件",
    "dataImport.parsing": "正在解析文件...",
    "dataImport.loginRequired": "請先登入系統再進行操作",
    "dataImport.previewTitle": "預覽",
    "dataImport.rowsDetected": "行數據，請確認導入類型",
    "dataImport.dataTypeLabel": "你要導入什麼數據？",
    "dataImport.cancel": "取消",
    "dataImport.importing": "正在導入數據庫...",
    "dataImport.confirmImport": "確認導入",
    "dataImport.rows": "條數據",
    "dataImport.previewNote": "（僅顯示前 5 行預覽）",
    "dataImport.history": "導入歷史",
    "dataImport.historyDesc": "最近的文件處理記錄",
    "dataImport.noHistory": "暫無導入記錄",
    "dataImport.success": "成功",
    "dataImport.failed": "失敗",
    "dataImport.total": "共",

    // ── 消息推送 ───────────────────────────────────
    "push.title": "消息推送",
    "push.subtitle": "向各區域銷售團隊發送通知消息",

    // ── 競爭對手 ───────────────────────────────────
    "competitors.title": "競爭對手",
    "competitors.subtitle": "追蹤與分析競爭對手情報",

    // ── 機器學習分析 ───────────────────────────────
    "ml.title": "全球戰略儀表板",
    "ml.subtitle": "基於 BHI 項目庫與 AI 混合推薦模型的商機分析系統",
    "ml.totalProjects": "項目總數",
    "ml.totalInvestment": "涉及投資總額",
    "ml.aiMatches": "AI 高匹配商機",
    "ml.searchPlaceholder": "搜尋項目、國家或推薦產品...",
    "ml.sectorChart": "行業投資熱度 (Top 8)",
    "ml.sectorPie": "行業分佈佔比",

    // ── 銷售漏斗 ───────────────────────────────
    "pipeline.title": "銷售漏斗",
    "pipeline.subtitle": "追蹤與分析各產品線及區域的商機儲備情況",
    "pipeline.selectPeriod": "選擇時間段",
    "pipeline.reserveAmount": "商機儲備金額",
    "pipeline.unitBillionHKD": "億港幣",
    "pipeline.unitBillion": "億",
    "pipeline.unitWan": "萬",
    "pipeline.unitWanHKD": "萬港幣",
    "pipeline.reserveDesc": "口徑：創建時間在近6個月成單率>30%且不含已歸檔取消的商機的港幣金額總值",
    "pipeline.lastYear": "上年",
    "pipeline.thisYear": "今年",
    "pipeline.structure": "商機結構分佈",
    "pipeline.low": "商機贏率 < 30%",
    "pipeline.medium": "30% ≤ 商機贏率 < 80%",
    "pipeline.high": "商機贏率 ≥ 80%",
    "pipeline.productDist": "商機金額分佈（按產品）",
    "pipeline.productUnit": "單位：萬港幣",
    "pipeline.trendTitle": "月度商機趨勢",
    "pipeline.trendDesc": "追蹤商機價值與數量隨時間的變化",
    "pipeline.amountBillion": "金額（億）",
    "pipeline.count": "數量",
    "pipeline.amountLegend": "金額（億港幣）",
    "pipeline.countLegend": "數量",
    "pipeline.productTitle": "產品商機分佈",
    "pipeline.productDesc": "按產品線細分的商機詳情",
    "pipeline.amount": "金額",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language") as Language;
    if (saved && (saved === "en" || saved === "zh-CN" || saved === "zh-TW")) return saved;
    if (typeof navigator !== "undefined") {
      if (navigator.language.startsWith("zh")) {
        return navigator.language.includes("TW") || navigator.language.includes("HK") ? "zh-TW" : "zh-CN";
      }
    }
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    const translation = translations[language][key];
    if (!translation) {
      const fallback = translations["en"][key];
      return fallback || key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}